version: '3.4'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - '8000:8080'
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins
    privileged: true
networks:
  jenkins:
volumes:
  jenkins-data:
